/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useEffect, useRef } from 'react'
import { useGLTF, useVideoTexture } from '@react-three/drei'
import { useGSAP } from '@gsap/react'
import { gsap } from 'gsap'
import { Vector2 } from 'three'
export default function DemoComputer(props) {
    const { nodes, materials } = useGLTF('/models/cyberpunk_laptop_concept_design512.glb')
    const txt = useVideoTexture(props.texture ? props.texture : '/assets/projects/portfolio.mp4')
    const group = useRef()
    useEffect(() => {
        if (txt) {
            txt.rotation = -Math.PI/2
            txt.center = new Vector2(0.35, 0.65)
            
        }
    }, [txt])
    useGSAP(() => {
        gsap.from(group.current.rotation, {
            y: Math.PI * 2,
            duration: 1,
            ease: 'power3.out',
        })
    }, [txt])
    return (
        <group {...props} dispose={null} ref={group} scale={1.6} >
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube004_Auto_01_0.geometry}
                material={materials.Auto_01}
                position={[0, -25.593, 7.313]}
                rotation={[-Math.PI / 2, 0, 0]}
                scale={100}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Keys_Auto_02_0.geometry}
                material={materials.Auto_02}
                position={[-72.227, -27.683, 35.45]}
                rotation={[-Math.PI / 2, 0, 0.002]}
                scale={100}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube006_Auto_03_0.geometry}
                material={materials.Auto_03}
                position={[17.369, -25.593, 7.313]}
                rotation={[-Math.PI / 2, 0, 0]}
                scale={100}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube_Auto_04_0.geometry}
                material={materials.Auto_04}
                position={[0, 50.454, -8.888]}
                rotation={[-1.943, 0, -Math.PI / 2]}
                scale={100}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube_Screen_0.geometry}
                material={materials.Screen}
                position={[0, 50.454, -8.888]}
                rotation={[-1.943, 0, -Math.PI / 2]}
                scale={100}
            >
                <meshBasicMaterial map={txt} />
            </mesh>
        </group>
    )
}

useGLTF.preload('/models/cyberpunk_laptop_concept_design512.glb')
